apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rywh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rywh
    app.kubernetes.io/part-of: hacbs-demo-test-app-bhld
  name: test-component-rywh
  namespace: appstudio-e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-rywh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-rywh
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:ae25f5f50749203cc8e597044f7166dfeaa89ad31940b2e7b7d538819f3743e9
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
