apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-rywh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-rywh
    app.kubernetes.io/part-of: hacbs-demo-test-app-bhld
  name: test-component-rywh
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-rywh
    weight: 100
status: {}
